export default function mapLanguage(lang) {
  if (lang === null) return 'comment';
  const languages = {
    bash: 'bash',
    git: 'bash',
    shell: 'bash',
    c: 'c',
    cmake: 'cmake',
    comment: 'comment',
    q: 'comment',
    cpp: 'cpp',
    'c++': 'cpp',
    cxx: 'cpp',
    cs: 'cs',
    csharp: 'cs',
    'c#': 'cs',
    css: 'css',
    dart: 'dart',
    elm: 'elm',
    gq: 'graphql',
    gql: 'graphql',
    graphql: 'graphql',
    html: 'html',
    java: 'java',
    javascript: 'javascript',
    js: 'javascript',
    json: 'json',
    kotlin: 'kotlin',
    less: 'less',
    mongo: 'mongo',
    mongodb: 'mongo',
    py: 'python',
    python: 'python',
    react: 'react',
    jsx: 'react',
    tsx: 'react',
    rust: 'rust',
    rs: 'rust',
    sass: 'sass',
    scss: 'scss',
    sql: 'sql',
    swift: 'swift',
    ts: 'typescript',
    tsc: 'typescript',
    typescript: 'typescript',
    vim: 'vim'
  }
  return languages[lang.toLowerCase()]
}