export const languageSelectOptions = {
    '': '',
    'typescript': 'TypeScript',
    'go': 'Go',
    'bash': 'Bash',
    'rust': 'Rust',
    'python': 'Python',
    'java': 'Java',
    'cpp': 'C++',
    'plaincode': 'Plain Code',
    'docker': 'Dockerfile',
    'yaml': 'YAML',
    'json': 'JSON',
    'toml': 'TOML',
    'javascript': 'JavaScript',
    'react': 'ReactJS',
    'c': 'C',
    'sql': 'SQL',
    'css': 'css',
    // 'mongo': 'MongoDB',
    'kotlin': 'Kotlin',
    'cs': 'C#',
    'graphql': 'GraphQL',
    'nginx': 'Nginx',
    'html': 'HTML',
    // 'cmake': 'CMake',
    // 'scss': 'SCSS',
    // 'less': 'Less'
  }